/// Written by: LadyYulia
/// Creation Date: 09th of December 2018
/// Purpose: Enumeration for the types of keys events
namespace KeyLogger
{
    public enum KeyStates
    {
        EscapeDown, EscapeUp,
        F1Down, F1Up,
        F2Down, F2Up,
        F3Down, F3Up,
        F4Down, F4Up,
        F5Down, F5Up,
        F6Down, F6Up,
        F7Down, F7Up,
        F8Down, F8Up,
        F9Down, F9Up,
        F10Down, F10Up,
        F11Down, F11Up,
        F12Down, F12Up,

        PrintScreenDown, PrintScreenUp,
        ScrollLockDown, ScrollLockUp,
        PauseDown, PauseUp,

        TildaDown, TildaUp,
        ExclamationDown, ExclamationUp,
        AtDown, AtUp,
        SharpDown, SharpUp,
        DollarDown, DollarUp,
        PercentDown, PercentUp,
        PowerDown, PowerUp,
        AmpDown, AmpUp,
        AsterixDown, AsterixUp,
        LeftRoundParentesysDown, LeftRoundParentesysUp,
        RightRoundParentesysDown, RightRoundParentesysUp,
        DashDown, DashUp,
        EqualDown, EqualUp,
        BackspaceDown, BackspaceUp,

        TabDown, TabUp,
        QDown, QUp,
        WDown, WUp,
        EDown, EUp,
        RDown, RUp,
        TDown, TUp,
        YDown, YUp,
        UDown, UUp,
        IDown, IUp,
        ODown, OUp,
        PDown, PUp,
        LeftSquareBracketDown, LeftSquareBracketUp,
        RightSquareBracketDown, RightSquareBracketUp,
        LeftCurlyBracketDown, LeftCurlyBracketUp,
        RightCurlyBracketDown, RightCurlyBracketUp,
        BackslashDown, BackslashUp,
        CapsDown, CapsUp,
        ADown, AUp,
        SDown, SUp,
        DDown, DUp,
        FDown, FUp,
        GDown, GUp,
        HDown, HUp,
        JDOwn, JUp,
        KDown, KUp,
        LDown, LUp,
        SemicolonDown, SemicolonUp,
        QuoteDown, QuoteUp,
        EnterDown, EnterUp,

        LeftShiftDown, LeftShiftUp,
        ZDown, ZUp,
        XDown, XUp,
        CDown, CUp,
        VDown, VUp,
        BDown, BUp,
        NDown, NUp,
        MDown, Mup,
        LeftAngleBracketDown, LeftAngleBracketUp,
        RightAngleBracketDown, RightAngleBracketUp,
        SlashDown, SlashUp,
        RightShiftDown, RightShiftUp,
        LeftCtrlDown, LeftCtrlUp,
        LeftWinDown, LeftWinUp,
        LeftAltDown, LeftAltUp,
        SpaceDown, SpaceUp,
        RightAltDown, RightAltUp,
        RightWinDown, RightWinUp,
        FnDown, FnUp,
        RightCtrlDown, RightCtrlUp,

        InsertDown, InsertUp,
        HomeDown, HomeUp,
        PageUpDown, PageUpUp,

        DeleteDown, DeleteUp,
        EndDown, EndUp,
        PageDownDown, PageDownUp,

        UpArrowDown, UpArrowUp,
        LeftArrowDown, LeftArrowUp,
        DownArrowDown, DownArrowUp,
        RightArrowDown, RightArrowUp,

        NumLockDown, NumLockUp,
        DivideDown, DivideUp,
        MultiplyDown, MultiplyUp,
        MinusDown, MinusUp,
        PlusDown, PlusUp,
        NumEnterDown, NumEnterUp,
        Num0Down, Num0Up,
        Num1Down, Num1Up,
        Num2Down, Num2Up,
        Num3Down, Num3Up,
        Num4Down, Num4Up,
        Num5Down, Num5Up,
        Num6Down, Num6Up,
        Num7Down, Num7Up,
        Num8Down, Num8Up,
        Num9Down, Num9Up,
        NumDotDown, NumDotUp
    }
}
